require "./db/seeds/schools.rb"
require "./db/seeds/users.rb"
require "./db/seeds/courses.rb"
require "./db/seeds/registrations.rb"
require "./db/seeds/decks.rb"
require "./db/seeds/cards.rb"
require "./db/seeds/tests.rb"
require "./db/seeds/responses.rb"
